<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="3" ignored="0" total="8" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="51207" started-at="2019-08-31T18:44:12Z" finished-at="2019-08-31T18:45:03Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="51207" started-at="2019-08-31T18:44:12Z" finished-at="2019-08-31T18:45:03Z">
      <class name="testcases.LoginFeaturePartTwo">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testcases.LoginFeaturePartTwo@59fa1d9b]" name="beforeMethod" is-config="true" duration-ms="4276" started-at="2019-08-31T18:44:19Z" finished-at="2019-08-31T18:44:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:testcases.LoginFeaturePartTwo@59fa1d9b]" name="beforeClass" is-config="true" duration-ms="0" started-at="2019-08-31T18:44:19Z" finished-at="2019-08-31T18:44:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="verifyLoginSuccess()[pri:1, instance:testcases.LoginFeaturePartTwo@59fa1d9b]" name="verifyLoginSuccess" duration-ms="1030" started-at="2019-08-31T18:44:23Z" description="To Verify Login Successful" finished-at="2019-08-31T18:44:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginSuccess -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testcases.LoginFeaturePartTwo@59fa1d9b]" name="afterMethod" is-config="true" duration-ms="665" started-at="2019-08-31T18:44:24Z" finished-at="2019-08-31T18:44:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testcases.LoginFeaturePartTwo@59fa1d9b]" name="beforeMethod" is-config="true" duration-ms="4220" started-at="2019-08-31T18:44:31Z" finished-at="2019-08-31T18:44:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="verifyLoginFailure()[pri:2, instance:testcases.LoginFeaturePartTwo@59fa1d9b]" name="verifyLoginFailure" duration-ms="411" started-at="2019-08-31T18:44:35Z" description="To Verify Login Unsuccessful" finished-at="2019-08-31T18:44:35Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at testcases.LoginFeaturePartTwo.verifyLoginFailure(LoginFeaturePartTwo.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginFailure -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testcases.LoginFeaturePartTwo@59fa1d9b]" name="afterMethod" is-config="true" duration-ms="655" started-at="2019-08-31T18:44:35Z" finished-at="2019-08-31T18:44:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testcases.LoginFeaturePartTwo@59fa1d9b]" name="beforeMethod" is-config="true" duration-ms="8685" started-at="2019-08-31T18:44:47Z" finished-at="2019-08-31T18:44:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="verifyQuickLunchCount()[pri:3, instance:testcases.LoginFeaturePartTwo@59fa1d9b]" name="verifyQuickLunchCount" duration-ms="1046" started-at="2019-08-31T18:44:56Z" description="To Verify count on Quick Launch" finished-at="2019-08-31T18:44:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [3] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [3] but found [0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at testcases.LoginFeaturePartTwo.verifyQuickLunchCount(LoginFeaturePartTwo.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyQuickLunchCount -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testcases.LoginFeaturePartTwo@59fa1d9b]" name="afterMethod" is-config="true" duration-ms="674" started-at="2019-08-31T18:44:57Z" finished-at="2019-08-31T18:44:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="verifyQuickLaunchText()[pri:4, instance:testcases.LoginFeaturePartTwo@59fa1d9b]" name="verifyQuickLaunchText" duration-ms="0" started-at="2019-08-31T18:45:03Z" description="To Verify Text on Quick Launch" depends-on-methods="testcases.LoginFeaturePartTwo.verifyQuickLunchCount" finished-at="2019-08-31T18:45:03Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LoginFeaturePartTwo.verifyQuickLaunchText()[pri:4, instance:testcases.LoginFeaturePartTwo@59fa1d9b] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LoginFeaturePartTwo.verifyQuickLaunchText()[pri:4, instance:testcases.LoginFeaturePartTwo@59fa1d9b] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyQuickLaunchText -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:testcases.LoginFeaturePartTwo@59fa1d9b]" name="afterClass" is-config="true" duration-ms="0" started-at="2019-08-31T18:45:03Z" finished-at="2019-08-31T18:45:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- testcases.LoginFeaturePartTwo -->
      <class name="testcases.LoginFeature">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:testcases.LoginFeature@d8355a8]" name="beforeSuite" is-config="true" duration-ms="8" started-at="2019-08-31T18:44:12Z" finished-at="2019-08-31T18:44:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:testcases.LoginFeature@d8355a8]" name="beforeTest" is-config="true" duration-ms="0" started-at="2019-08-31T18:44:12Z" finished-at="2019-08-31T18:44:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:testcases.LoginFeature@d8355a8]" name="beforeClass" is-config="true" duration-ms="1" started-at="2019-08-31T18:44:12Z" finished-at="2019-08-31T18:44:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testcases.LoginFeature@d8355a8]" name="beforeMethod" is-config="true" duration-ms="4738" started-at="2019-08-31T18:44:12Z" finished-at="2019-08-31T18:44:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="verifyLoginSuccess()[pri:1, instance:testcases.LoginFeature@d8355a8]" name="verifyLoginSuccess" duration-ms="855" started-at="2019-08-31T18:44:17Z" description="To Verify Login Successful" finished-at="2019-08-31T18:44:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginSuccess -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testcases.LoginFeature@d8355a8]" name="afterMethod" is-config="true" duration-ms="664" started-at="2019-08-31T18:44:18Z" finished-at="2019-08-31T18:44:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testcases.LoginFeature@d8355a8]" name="beforeMethod" is-config="true" duration-ms="5015" started-at="2019-08-31T18:44:24Z" finished-at="2019-08-31T18:44:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="verifyLoginFailure()[pri:2, instance:testcases.LoginFeature@d8355a8]" name="verifyLoginFailure" duration-ms="368" started-at="2019-08-31T18:44:29Z" description="To Verify Login Unsuccessful" finished-at="2019-08-31T18:44:30Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at testcases.LoginFeature.verifyLoginFailure(LoginFeature.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginFailure -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testcases.LoginFeature@d8355a8]" name="afterMethod" is-config="true" duration-ms="671" started-at="2019-08-31T18:44:30Z" finished-at="2019-08-31T18:44:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testcases.LoginFeature@d8355a8]" name="beforeMethod" is-config="true" duration-ms="8760" started-at="2019-08-31T18:44:36Z" finished-at="2019-08-31T18:44:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="verifyQuickLunchCount()[pri:3, instance:testcases.LoginFeature@d8355a8]" name="verifyQuickLunchCount" duration-ms="1884" started-at="2019-08-31T18:44:45Z" description="To Verify count on Quick Launch" finished-at="2019-08-31T18:44:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyQuickLunchCount -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testcases.LoginFeature@d8355a8]" name="afterMethod" is-config="true" duration-ms="698" started-at="2019-08-31T18:44:46Z" finished-at="2019-08-31T18:44:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testcases.LoginFeature@d8355a8]" name="beforeMethod" is-config="true" duration-ms="3984" started-at="2019-08-31T18:44:58Z" finished-at="2019-08-31T18:45:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="verifyQuickLaunchText()[pri:4, instance:testcases.LoginFeature@d8355a8]" name="verifyQuickLaunchText" duration-ms="1163" started-at="2019-08-31T18:45:02Z" description="To Verify Text on Quick Launch" depends-on-methods="testcases.LoginFeature.verifyQuickLunchCount" finished-at="2019-08-31T18:45:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyQuickLaunchText -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testcases.LoginFeature@d8355a8]" name="afterMethod" is-config="true" duration-ms="698" started-at="2019-08-31T18:45:03Z" finished-at="2019-08-31T18:45:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:testcases.LoginFeature@d8355a8]" name="afterClass" is-config="true" duration-ms="0" started-at="2019-08-31T18:45:03Z" finished-at="2019-08-31T18:45:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:testcases.LoginFeature@d8355a8]" name="afterTest" is-config="true" duration-ms="0" started-at="2019-08-31T18:45:03Z" finished-at="2019-08-31T18:45:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:testcases.LoginFeature@d8355a8]" name="afterSuite" is-config="true" duration-ms="0" started-at="2019-08-31T18:45:03Z" finished-at="2019-08-31T18:45:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- testcases.LoginFeature -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
